/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [UserId]
      ,[Role]
      ,[FirstName]
      ,[LastName]
      ,[EmailId]
      ,[MobileNumber]
      ,[AddressInfo]
      ,[City]
      ,[UserState]
      ,[Pincode]
      ,[Password]
      ,[IsLogin]
  FROM [ShoppingZoneDB].[dbo].[UserDetails]